/**
 * sync-configs.ts
 *
 * Reads config/config-sources.json and writes all generated tool config files.
 * Run after any change to config-sources.json.
 *
 * Run: npm run sync:configs
 */

import fs from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCES_PATH = path.join(ROOT, "config/config-sources.json");

type McpServerEntry = {
  command: string;
  args: string[];
  type: string;
  _docs?: string;
  _purpose?: string;
  _pinned_version?: string;
  [key: string]: unknown;
};

type Sources = {
  _meta: { schema_version: string };
  mcpServers: Record<string, McpServerEntry>;
  toolTargets: Record<string, { outputPath: string }>;
};

function log(msg: string) { console.log(msg); }

log("\n── Syncing configs from config-sources.json\n");

const sources: Sources = JSON.parse(fs.readFileSync(SOURCES_PATH, "utf8"));

// Strip internal _meta keys from server entries — only keep real config fields
function cleanServer(entry: McpServerEntry): Record<string, unknown> {
  const cleaned: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(entry)) {
    if (!k.startsWith("_")) cleaned[k] = v;
  }
  return cleaned;
}

const cleanedServers = Object.fromEntries(
  Object.entries(sources.mcpServers).map(([name, entry]) => [name, cleanServer(entry)])
);

for (const [toolName, target] of Object.entries(sources.toolTargets)) {
  const outputPath = path.join(ROOT, target.outputPath);
  const config = {
    _generated: "Auto-generated by sync-configs.ts from config/config-sources.json. Do not edit directly.",
    mcpServers: cleanedServers,
  };

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(config, null, 2) + "\n");
  log(`  ✓  ${toolName} → ${target.outputPath}`);
}

// Stamp sources with sync time
sources._meta = {
  ...sources._meta,
  // @ts-ignore
  last_synced: new Date().toISOString(),
};
fs.writeFileSync(SOURCES_PATH, JSON.stringify(sources, null, 2) + "\n");

log("\n✅ All configs synced.\n");
log("   Next: run npm run check:configs to verify\n");
